import { chromium } from 'playwright-core';
import { serve } from './serve.mjs';
const { server, url } = await serve(0);
const b = await chromium.launch({ headless: true, args: ['--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1240, height: 1080 }, deviceScaleFactor: 1 });
await p.goto(`${url}/demo/tmp/grid.html`, { waitUntil: 'networkidle' });
await p.waitForTimeout(600);
await p.screenshot({ path: '/home/john/screenshots/2026-08-08-paperweb/four-approaches.png', fullPage: true });
console.log('wrote four-approaches.png');
await b.close(); server.close();
